---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint handlers defaults meta molecule tasks templates tests vars
  ansible-lint .
  flake8 --exclude=.venv
platforms:
  - name: docker-test
    box: debian/buster64
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
verifier:
  name: testinfra
  options:
    v: 1
